#!/bin/sh

# Gerrit captures only stdout
exec 2>&1

die() {
    local m="$1"
    echo "FATAL: ${m}" >&2
    exit 1
}

[ -n "${GERRIT_SITE}" ] || die "Please set GERRIT_SITE"

. "${GERRIT_SITE}/etc/checks-mock.conf" || die "Cannot read configuration '${GERRIT_SITE}/etc/checks-mock.conf'"

[ -n "${GERRIT_CHECKS_MOCK_URL}" ] || die "GERRIT_CHECKS_MOCK_URL is missing"
[ -n "${GERRIT_CHECKS_REF_PREFIX}" ] || die "GERRIT_CHECKS_REF_PREFIX is missing"

while [ -n "$1" ]; do
    case "$1" in
        --change)
            CHANGE="$2"
            shift 2
            ;;
        --patchset)
            REVISION="$2"
            shift 2
            ;;
        --commit)
            COMMIT="$2"
            shift 2
            ;;
        --*)
            shift 2
            ;;
        *)
            break
            ;;
    esac
done

[ -n "${CHANGE}" ] || die "Cannot parse change"
[ -n "${REVISION}" ] || die "Cannot parse patchset"
[ -n "${COMMIT}" ] || die "Cannot parse commit"

# Gerrit uses '~' as separator which is illegal in refspec
# As it URL encode the parts, we can use '#' as replacement
CHANGE="$(echo "${CHANGE}" | sed 's/~/#/g')"

REF="${COMMIT}:refs/heads/${GERRIT_CHECKS_REF_PREFIX}/${CHANGE}/${REVISION}"
echo "git push --force '${GERRIT_CHECKS_MOCK_URL}' '${REF}'"
git push --force "${GERRIT_CHECKS_MOCK_URL}" "${REF}" || die "Failed to push to ${GERRIT_CHECKS_MOCK_URL}"

exit 0
